name: Github Actions Demo

on:
  push:
    branches:
      - main

jobs:
  python-version:
    runs-on: ubuntu-latest
    steps:
      - name: pokaz wersje pythona
        run: python --version
  testowanie :
      runs-on: ubuntu-latest
      steps:
        - name: wlacz pylint
          run: pylint ./app.py
        
      
