name: Github Actions Demo

on:
  push:
    branches:
      - main

jobs:
  python-version:
    runs-on: ubuntu-latest
    steps:
      - name: Show Python version
        run: python --version

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Pylint
        run: pylint app.py
